name: Publish package

on:
  push:
    tags: ['*']

jobs:
  node:
    name: Publish Node package
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/tree-sitter-arduino
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install packages
        run: npm install
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  rust:
    name: Publish Rust package
    runs-on: ubuntu-latest
    environment:
      name: crates
      url: https://crates.io/crates/tree-sitter-arduino
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_TOKEN}}
